version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: apt-get
          command: apt update && apt -y install build-essential gcc g++ cmake git wget libgoogle-glog-dev libboost-test-dev libboost-filesystem-dev libboost-serialization-dev libboost-system-dev pkg-config libeigen3-dev libclass-loader-dev libtinyxml-dev
      - run:
          name: download install script
          command: wget https://raw.githubusercontent.com/envire/envire-envire_core/master/install_standalone.sh
      - run:
          name: chmod install script
          command: chmod +x install_standalone.sh
      - run:
          name: run install script
          command: ./install_standalone.sh
